name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * 1' # every 30 minutes
  workflow_dispatch:
    
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: fym35
          base: master
          head: master
